source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vi.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/mappings.zsh
source ~/.config/zsh/config.zsh


source ~/.config/.zsh-autopair/autopair.zsh
autopair-init
source ~/.config/.zim/init.zsh
source ~/.config/.zim/modules/fzf-tab/fzf-tab.plugin.zsh

