source $HOME/.config/zsh/env.zsh
source $HOME/.config/zsh/aliases.zsh
source $HOME/.config/zsh/plugins.zsh
source $HOME/.config/zsh/vi.zsh
source $HOME/.config/zsh/fzf.zsh
source $HOME/.config/zsh/mappings.zsh
source $HOME/.config/zsh/config.zsh
source $HOME/.config/.zsh-autopair/autopair.zsh
source $HOME/.zim/init.zsh
source $HOME/.zim/modules/fzf-tab/fzf-tab.plugin.zsh

# steup something...
autopair-init
eval "$(starship init zsh)"
eval "$(fnm env)"
source /etc/profile
